CREATE TABLE DEPARTMENT(
	DNO INT PRIMARY KEY,
	DNAME VARCHAR(20) NOT NULL
);

CREATE TABLE EMPLOYEE(
 	SSN VARCHAR(10) PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
    SALARY INT NOT NULL,
    DEPT INT,
    FOREIGN KEY(DEPT) REFERENCES DEPARTMENT(DNO)
);

CREATE TABLE PROJECT(
	PNO INT PRIMARY KEY,
	DOMAIN VARCHAR(20) NOT NULL
);

CREATE TABLE WORKS_ON(
	SSN VARCHAR(10),
    PNO INT,
    HOURS INT,
    FOREIGN KEY(SSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY(PNO) REFERENCES PROJECT(PNO),
    PRIMARY KEY(SSN,PNO)
);

INSERT INTO DEPARTMENT VALUES(
  	1,
  	'ACCOUNTS'
);

//Simple Query:
SELECT * FROM EMPLOYEE WHERE SSN IN
(SELECT SSN FROM WORKS_ON WHERE PNO IN
(SELECT PNO FROM PROJECT WHERE DOMAIN='DATABASE'));

SELECT DEPT, COUNT(SSN) FROM EMPLOYEE
GROUP BY DEPT
ORDER BY DEPT;

UPDATE WORKS_ON SET PNO=1 WHERE SSN='1MS20IS128' AND PNO=2;

SELECT SSN, COUNT(PNO) FROM WORKS_ON
GROUP BY SSN
HAVING COUNT(PNO)<3;

//complex version
SELECT * FROM EMPLOYEE WHERE SSN IN
(SELECT SSN FROM WORKS_ON WHERE PNO IN
(SELECT PNO FROM PROJECT WHERE DOMAIN='DATABASE'));

SELECT DEPT, DNAME, COUNT(SSN) FROM EMPLOYEE, DEPARTMENT
WHERE DEPT=DNO
GROUP BY DEPT,DNAME
ORDER BY DEPT;

UPDATE WORKS_ON SET PNO=1 WHERE SSN='1MS20IS128' AND PNO=2;

SELECT WORKS_ON.SSN, ENAME, COUNT(PNO) FROM WORKS_ON, EMPLOYEE
WHERE WORKS_ON.SSN=EMPLOYEE.SSN
GROUP BY WORKS_ON.SSN, EMPLOYEE.ENAME
HAVING COUNT(PNO)<3;

//plsql
edit filename.sql
BEGIN
    UPDATE EMPLOYEE
    SET SALARY=(1.15*SALARY)    
    WHERE DEPT=2;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT||'ROWS UPDATED');
END;
/

set serveroutput on
@filename.sql

//mongodb
db.createCollection("Employee")
db.Employee.insertMany([
    {'SSN':"1MS20IS100",'Name':"Ryan",'Department':"IT",'ProjNo':1},
    {'SSN':"1MS20IS101",'Name':"Saket",'Department':"IT",'ProjNo':2}
    ])
    
db.Employee.find({'Department':"IT"}).pretty()
db.Employee.find({'ProjNo':2}).pretty()



